name: Update Rate

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 3,10 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'rate')

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.UPDATE_WORKFLOW }}
    - name: Checkout gh
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: dist
        token: ${{ secrets.UPDATE_WORKFLOW }}
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Get Rate
      run: |
        yarn --frozen-lockfile && node ./index.js --COOKIE=${{ secrets.COOKIE }}
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        commit_message: Update rate
        build_dir: dist
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
