name: Update Rate

on:
  schedule:
    - cron:  '0 10 * * *'
  push:
    branches: [ master ]
    paths:
      - '*.js'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.UPDATE_WORKFLOW }}
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Get Rate
      run: |
        yarn --frozen-lockfile
        node index.js
    - name: Commit changes
      run: |
        git add --a
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "tenka"
        echo "::set-env name=commit_state::$(git commit -m 'Update next time' | tr '\n' ' ' | cut -c50-100)"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.UPDATE_WORKFLOW }}
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        commit_message: Update rate
        build_dir: dist
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}